// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type CampaignListReq struct {
	CampaignId   string `json:"campaign_id"`
	CampaignName string `json:"campaign_name"`
	Page         int64  `json:"page"`
	PageSize     int64  `json:"page_size"`
}

type CampaignListResp struct {
	BaseResp
	Total int64           `json:"total"`
	Data  []*CampaignInfo `json:"data"`
}

type CampaignInfo struct {
	Id           int64  `json:"id"`
	CampaignId   string `json:"campaign_id"`
	CampaignName string `json:"campaign_name"`
}
