// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb/marketing.proto

package marketing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketingCenterClient is the client API for MarketingCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketingCenterClient interface {
	PromotionCreate(ctx context.Context, in *PromotionCreateReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type marketingCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingCenterClient(cc grpc.ClientConnInterface) MarketingCenterClient {
	return &marketingCenterClient{cc}
}

func (c *marketingCenterClient) PromotionCreate(ctx context.Context, in *PromotionCreateReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, "/marketing.MarketingCenter/PromotionCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingCenterServer is the server API for MarketingCenter service.
// All implementations must embed UnimplementedMarketingCenterServer
// for forward compatibility
type MarketingCenterServer interface {
	PromotionCreate(context.Context, *PromotionCreateReq) (*BaseResp, error)
	mustEmbedUnimplementedMarketingCenterServer()
}

// UnimplementedMarketingCenterServer must be embedded to have forward compatible implementations.
type UnimplementedMarketingCenterServer struct {
}

func (UnimplementedMarketingCenterServer) PromotionCreate(context.Context, *PromotionCreateReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromotionCreate not implemented")
}
func (UnimplementedMarketingCenterServer) mustEmbedUnimplementedMarketingCenterServer() {}

// UnsafeMarketingCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingCenterServer will
// result in compilation errors.
type UnsafeMarketingCenterServer interface {
	mustEmbedUnimplementedMarketingCenterServer()
}

func RegisterMarketingCenterServer(s grpc.ServiceRegistrar, srv MarketingCenterServer) {
	s.RegisterService(&MarketingCenter_ServiceDesc, srv)
}

func _MarketingCenter_PromotionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromotionCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingCenterServer).PromotionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketing.MarketingCenter/PromotionCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingCenterServer).PromotionCreate(ctx, req.(*PromotionCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketingCenter_ServiceDesc is the grpc.ServiceDesc for MarketingCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketingCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketing.MarketingCenter",
	HandlerType: (*MarketingCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PromotionCreate",
			Handler:    _MarketingCenter_PromotionCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/marketing.proto",
}
