// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"business/app/account/rpc/account"
	"business/app/account/rpc/internal/logic"
	"business/app/account/rpc/internal/svc"
)

type AccountCenterServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountCenterServer
}

func NewAccountCenterServer(svcCtx *svc.ServiceContext) *AccountCenterServer {
	return &AccountCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountCenterServer) AccountCreate(ctx context.Context, in *account.AccountCreateReq) (*account.BaseResp, error) {
	l := logic.NewAccountCreateLogic(ctx, s.svcCtx)
	return l.AccountCreate(in)
}

func (s *AccountCenterServer) AccountUpdate(ctx context.Context, in *account.AccountUpdateReq) (*account.BaseResp, error) {
	l := logic.NewAccountUpdateLogic(ctx, s.svcCtx)
	return l.AccountUpdate(in)
}

func (s *AccountCenterServer) GetAccountInfo(ctx context.Context, in *account.AccountInfoReq) (*account.AccountInfo, error) {
	l := logic.NewGetAccountInfoLogic(ctx, s.svcCtx)
	return l.GetAccountInfo(in)
}

func (s *AccountCenterServer) GetAccountByClientId(ctx context.Context, in *account.GetTokenReq) (*account.AccountInfo, error) {
	l := logic.NewGetAccountByClientIdLogic(ctx, s.svcCtx)
	return l.GetAccountByClientId(in)
}

func (s *AccountCenterServer) AccountList(ctx context.Context, in *account.AccountListReq) (*account.AccountListResp, error) {
	l := logic.NewAccountListLogic(ctx, s.svcCtx)
	return l.AccountList(in)
}

func (s *AccountCenterServer) AccountSearch(ctx context.Context, in *account.AccountSearchReq) (*account.AccountSearchResp, error) {
	l := logic.NewAccountSearchLogic(ctx, s.svcCtx)
	return l.AccountSearch(in)
}

func (s *AccountCenterServer) GetAccountsByAccountIds(ctx context.Context, in *account.GetByAccountIdsReq) (*account.AccountSearchResp, error) {
	l := logic.NewGetAccountsByAccountIdsLogic(ctx, s.svcCtx)
	return l.GetAccountsByAccountIds(in)
}

func (s *AccountCenterServer) GetDefaultAccountList(ctx context.Context, in *account.DefaultListReq) (*account.AccountSearchResp, error) {
	l := logic.NewGetDefaultAccountListLogic(ctx, s.svcCtx)
	return l.GetDefaultAccountList(in)
}

func (s *AccountCenterServer) GetParentAccountList(ctx context.Context, in *account.ParentListReq) (*account.AccountSearchResp, error) {
	l := logic.NewGetParentAccountListLogic(ctx, s.svcCtx)
	return l.GetParentAccountList(in)
}

func (s *AccountCenterServer) GetToken(ctx context.Context, in *account.GetTokenReq) (*account.TokenInfo, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}

func (s *AccountCenterServer) SetToken(ctx context.Context, in *account.TokenInfo) (*account.BaseResp, error) {
	l := logic.NewSetTokenLogic(ctx, s.svcCtx)
	return l.SetToken(in)
}
