// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"business/app/marketing/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware, serverCtx.PermissionMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/token",
					Handler: accessTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/refresh",
					Handler: refreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/promotion/create",
					Handler: promotionCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/promotion/list",
					Handler: promotionListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/list",
					Handler: accountListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/auth",
					Handler: accountAuthHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/info",
					Handler: accountInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/create",
					Handler: accountCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/update",
					Handler: accountUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/marketing"),
	)
}
