// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type UserBase struct {
	Username string `json:"username" validate:"required"`
	Email    string `json:"email" validate:"required,email"`
	Mobile   string `json:"mobile"`
}

type UserCreateReq struct {
	UserBase
	Pass   string `json:"pass" validate:"required,password"`
	RoleId int64  `json:"role_id" validate:"required"`
}

type RoleCreateReq struct {
	RoleName string `json:"role_name" validate:"required"`
	Sys      int64  `json:"sys" validate:"numeric"`
}

type UserUpdateReq struct {
	Id int64 `json:"id" validate:"required"`
	UserBase
	Pass   string `json:"pass" validate:"omitempty,password"`
	State  int64  `json:"state" validate:"numeric"`
	RoleId int64  `json:"role_id" validate:"required"`
}

type RoleUpdateReq struct {
	Id       int64  `json:"id" validate:"required"`
	RoleName string `json:"role_name" validate:"required"`
	State    int64  `json:"state" validate:"numeric"`
}

type Login struct {
	Email string `json:"email" validate:"required,email"`
	Pass  string `json:"pass" validate:"required,password"`
}

type LoginResp struct {
	BaseResp
	Data LoginTokenResp `json:"data"`
}

type LoginTokenResp struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	RoleId   int64  `json:"role_id"`
	Token    string `json:"token"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserDestroyReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type ProfileResp struct {
	BaseResp
	Data ProfileInfo `json:"data"`
}

type ProfileInfo struct {
	UserInfo
	Permissions []string `json:"permissions"`
}

type UserInfo struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	Mobile    string   `json:"mobile"`
	State     int64    `json:"state"`
	CreatedAt int64    `json:"created_at"`
	Role      RoleInfo `json:"role"`
}

type RoleInfo struct {
	Id       int64  `json:"id"`
	RoleName string `json:"role_name"`
	State    int64  `json:"state"`
}

type RoleInfoReq struct {
	Id int64 `json:"id"`
}

type RoleDestroyReq struct {
	Id int64 `json:"id"`
}

type RoleInfoResp struct {
	BaseResp
	Data RoleInfo `json:"data"`
}

type UserListReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	State    int64  `json:"state"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
}

type UserListResp struct {
	BaseResp
	Total int64      `json:"total"`
	Data  []UserInfo `json:"data"`
}

type RoleListReq struct {
	RoleName string `json:"role_name"`
	State    int64  `json:"state"`
}

type RoleListResp struct {
	BaseResp
	Data []RoleInfo `json:"data"`
}
