// Code generated by goctl. DO NOT EDIT.
package types

type Dictionary struct {
	Id       string        `json:"id"`
	Pid      string        `json:"pid"`
	Label    string        `json:"label"`
	Value    string        `json:"value"`
	Children []*Dictionary `json:"children"`
}

type DictReq struct {
	DictKey string `form:"dict_key"`
}

type DictResp struct {
	BaseResp
	Data map[string][]*Dictionary `json:"data"`
}

type ContinentCountry struct {
	Continents []*Continent `json:"continents"`
	Countries  []*Country   `json:"countries"`
}

type Continent struct {
	Id    int64  `json:"id"`
	CName string `json:"c_name"`
}

type Country struct {
	CId         string `json:"c_id"`
	CCode       string `json:"c_code"`
	CName       string `json:"c_name"`
	ContinentId int64  `json:"continent_id"`
}

type LocationResp struct {
	BaseResp
	Data ContinentCountry `json:"data"`
}

type AdsMapResourceResp struct {
	BaseResp
	Data map[string]string `json:"data"`
}

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type CampaignCreateReq struct {
	AppId        string `json:"app_id"`                                          // 应用 ID
	CampaignName string `json:"campaign_name" validate:"required"`               // 计划名称
	ProductType  string `json:"product_type" validate:"required,product_type"`   // 推广产品
	DailyBudget  int64  `json:"daily_budget" validate:"numeric"`                 // 日预算
	CampaignType string `json:"campaign_type" validate:"required,campaign_type"` // 计划类型
	SyncFlow     string `json:"sync_flow_resource_searchad"`                     // 同时同步投放搜索广告网络
}

type CampaignCreateInfo struct {
	CampaignId string `json:"campaign_id"`
}

type CampaignCreateResp struct {
	Code int64               `json:"code"`
	Msg  string              `json:"msg"`
	Data *CampaignCreateInfo `json:"data"`
}

type CampaignListReq struct {
	Page         int64  `form:"page"`
	PageSize     int64  `form:"page_size"`
	CampaignName string `form:"campaign_name,optional"`
	CampaignId   string `form:"campaign_id,optional"`
	CampaignType string `form:"show_status,optional"`
	AppId        string `form:"app_id,optional"`
}

type Campaign struct {
	Id                        int64   `json:"id"`
	CampaignName              string  `json:"campaign_name"`                // 计划名称
	CampaignType              string  `json:"campaign_type"`                // 计划类型
	AccountId                 int64   `json:"account_id"`                   //
	AppId                     string  `json:"app_id"`                       // 应用 ID
	AdvertiserId              string  `json:"advertiser_id"`                //
	FlowResource              string  `json:"flow_resource"`                // 投放网络
	ProductType               string  `json:"product_type"`                 // 推广产品
	UserBalanceStatus         string  `json:"user_balance_status"`          // 账户余额状态
	OptStatus                 string  `json:"opt_status"`                   // 操作状态
	CampaignDailyBudgetStatus string  `json:"campaign_daily_budget_status"` // 计划日预算状态
	ShowStatus                string  `json:"show_status"`                  // 计划状态
	MarketingGoal             string  `json:"marketing_goal"`               //
	CampaignId                string  `json:"campaign_id"`                  // 计划ID
	TodayDailyBudget          int64   `json:"today_daily_budget"`           // 当日计划日限额
	TomorrowDailyBudget       int64   `json:"tomorrow_daily_budget"`        // 次日计划日限额，不返回表示与当日计划日限额相同
	SyncFlowResourceSearchad  string  `json:"sync_flow_resource_searchad"`  // 同时同步投放搜索广告网络 YES|NO
	IsCallback                int64   `json:"is_callback"`
	CreatedAt                 int64   `json:"created_at"` // 计划创建的时间
	UpdatedAt                 int64   `json:"updated_at"`
	App                       AppInfo `json:"app"`
}

type AppInfo struct {
	ProductId           string `json:"product_id"` // 产品ID
	AppName             string `json:"app_name"`
	IconUrl             string `json:"icon_url"`
	AppStoreDownloadUrl string `json:"app_store_download_url"`
}

type CampaignListResp struct {
	BaseResp
	Data CampaignListData `json:"data"`
}

type CampaignListData struct {
	Campaigns []*Campaign `json:"campaigns"`
	Total     int64       `json:"total"`
}

type Resources struct {
	OptStatus       map[string]string `json:"opt_status"`
	ProductType     map[string]string `json:"product_type"`
	CampaignType    map[string]string `json:"campaign_type"`
	SyncFlow        map[string]string `json:"sync_flow"`
	DailyBudgetOpts map[string]string `json:"daily_budget_opts"`
	ShowStatus      map[string]string `json:"show_status"`
	CampaignDaily   map[string]string `json:"campaign_daily"`
	BalanceStatus   map[string]string `json:"balance_status"`
	FlowResource    map[string]string `json:"flow_resource"`
}

type CampaignResources struct {
	BaseResp
	Data *Resources `json:"data"`
}

type CampaignInfoReq struct {
	CampaignId string `form:"campaign_id"`
}

type CampaignInfoResp struct {
	BaseResp
	Data Campaign `json:"data"`
}

type CampaignBindAppReq struct {
	CampaignIds []string `json:"campaign_ids"`
	AppId       string   `json:"app_id"`
}

type SyncAssetReq struct {
	AppId string `form:"app_id"`
}

type AssetListReq struct {
	Page      int64  `form:"page"`
	PageSize  int64  `form:"page_size"`
	AssetType string `form:"asset_type,optional"`
	Width     int64  `form:"width,optional"`
	Height    int64  `form:"height,optional"`
	AppId     string `form:"app_id,optional"`
}

type AssetListResp struct {
	BaseResp
	Data AssetListData `json:"data"`
}

type AssetListData struct {
	Total     int64             `json:"total"`
	List      []*Asset          `json:"list"`
	AssetType map[string]string `json:"asset_type"`
}

type Asset struct {
	AppId             string `json:"app_id"`
	AccountId         int64  `json:"account_id"`
	AdvertiserId      string `json:"advertiser_id"`
	AssetId           int64  `json:"asset_id"`
	AssetName         string `json:"asset_name"`
	AssetType         string `json:"asset_type"`
	FileUrl           string `json:"file_url"`
	Width             int64  `json:"width"`
	Height            int64  `json:"height"`
	VideoPlayDuration int64  `json:"video_play_duration"`
	FileSize          int64  `json:"file_size"`
	FileFormat        string `json:"file_format"`
	FileHashSha256    string `json:"file_hash_sha256"`
}

type AssetDeleteReq struct {
	AccountId    int64   `json:"account_id" validate:"required"`
	AdvertiserId string  `json:"advertiser_id" validate:"required"`
	AssetIds     []int64 `json:"asset_ids" validate:"required"`
}

type AssetUploadReq struct {
	AppId     string `form:"app_id" validate:"required"`
	AssetType string `form:"asset_type" validate:"required"`
	FileToken string `form:"file_token" validate:"required"`
	Duration  int64  `form:"duration" validate:"numeric"`
	Width     int64  `form:"width" validate:"required"`
	Height    int64  `form:"height" validate:"required"`
}

type AssetFileTokenReq struct {
	AppId string `form:"app_id"`
}

type AssetFileTokenResp struct {
	BaseResp
	Data string `json:"data"`
}

type AssetDimensionResp struct {
	BaseResp
	Data map[string][]string `json:"data"`
}

type AssetBindReq struct {
	AppId    string  `json:"app_id" validate:"required"`
	AssetIds []int64 `json:"asset_ids" validate:"required"`
}

type TargetingCreateReq struct {
	CampaignId         string     `json:"campaign_id"`
	TargetingType      string     `json:"targeting_type"`
	TargetingName      string     `json:"targeting_name"`
	Gender             string     `json:"gender"`
	Age                []string   `json:"age"`
	NetworkType        []string   `json:"network_type"`
	Location           string     `json:"location"`
	LocationType       string     `json:"location_type"`
	IncludeLocation    []string   `json:"include_location"`
	ExcludeLocation    []string   `json:"exclude_location"`
	Carrier            string     `json:"carrier"`
	Carriers           [][]string `json:"carriers"`
	AppCategory        string     `json:"app_category"`
	AppCategories      []string   `json:"app_categories"`
	AppInterest        string     `json:"app_interest"`
	AppInterests       [][]string `json:"app_interests"`
	Audience           string     `json:"audience"`
	Audiences          []string   `json:"audiences"`
	NotAudience        []string   `json:"not_audience"`
	SeriesType         string     `json:"series_type"`
	Series             []string   `json:"series"`
	MediaAppCategory   string     `json:"media_app_category"`
	AppCategoryOfMedia [][]string `json:"app_category_of_media"`
	LanguageCheck      string     `json:"language_check"`
	Language           []string   `json:"language"`
	InstalledApps      string     `json:"installed_apps"`
}

type TargetingCreateRsInfo struct {
	TargetingId int64 `json:"targeting_id"`
}

type TargetingCreateResp struct {
	BaseResp
	Data TargetingCreateRsInfo `json:"data"`
}

type TargetingListItem struct {
	TargetingId int64 `json:"targeting_id"`
	TargetingCreateReq
}

type TargetingListReq struct {
	CampaignId string `form:"campaign_id"`
}

type TargetingListResp struct {
	BaseResp
	Data []*TargetingListItem `json:"data"`
}

type TrackingListReq struct {
	AppId string `form:"app_id"`
}

type TrackingListResp struct {
	BaseResp
	Data []*TrackingItem `json:"data"`
}

type TrackingItem struct {
	EffectName string `json:"effect_name"`
	EffectType string `json:"effect_type"`
	TrackingId int64  `json:"tracking_id"`
}

type PositionQueryReq struct {
	Category    string `form:"category"`
	AccountId   int64  `form:"account_id"`
	ProductType string `form:"product_type"`
}

type PositionQueryResp struct {
	BaseResp
	Data []*PositionInfo `json:"data"`
}

type PositionInfo struct {
	CreativeSizeId              string           `json:"creative_size_id"`
	CreativeSizeNameDsp         string           `json:"creative_size_name_dsp"`
	CreativeSizeNameDescription string           `json:"creative_size_description"`
	SupportProductType          string           `json:"support_product_type"`
	IsSupportTimePeriod         string           `json:"is_support_time_period"`
	IsSupportMultipleCreatives  string           `json:"is_support_multiple_creatives"`
	SupportPriceType            string           `json:"support_price_type"`
	Samples                     []*SampleInfo    `json:"samples"`
	Placements                  []*PlacementInfo `json:"placements"`
}

type PositionPriceReq struct {
	CreativeSizeId string `form:"creative_size_id"`
	PriceType      string `form:"price_type"`
}

type PositionPriceResp struct {
	BaseResp
	Data float64 `json:"data"`
}

type SampleInfo struct {
	CreativeSizeSample string `json:"creative_size_ample"`
	PreviewTitle       string `json:"preview_title"`
}

type PlacementInfo struct {
	PlacementSizeId     string `json:"placement_size_id"`
	CreativeSize        string `json:"creative_size"`
	CreativeSizeSubType string `json:"creative_size_sub_type"`
}

type PositionPlacementReq struct {
	CreativeSizeId string `form:"creative_size_id"`
}

type PositionPlacementResp struct {
	*BaseResp
	Data PlacementResp `json:"data"`
}

type PlacementResp struct {
	Placements map[string][]string `json:"placements"`
	SubTypes   map[string]string   `json:"sub_types"`
}

type PositionElementReq struct {
	CreativeSizeId string `json:"creative_size_id" validate:"required"`
	CreativeSize   string `json:"creative_size" validate:"required,creativeSize"`
	SubType        string `json:"sub_type" validate:"required"`
}

type PositionElementResp struct {
	*BaseResp
	Data []*ElementItem `json:"data"`
}

type ElementItem struct {
	ElementId       string `json:"element_id"`
	ElementName     string `json:"element_name"`
	ElementTitle    string `json:"element_title"`
	ElementCaption  string `json:"element_caption"`
	MinLength       int64  `json:"min_length"`
	MaxLength       int64  `json:"max_length"`
	Width           int64  `json:"width"`
	Height          int64  `json:"height"`
	FileSizeKBLimit int64  `json:"file_size_kb_limit"`
	MinWidth        int64  `json:"min_width"`
	MinHeight       int64  `json:"min_height"`
	GifSizeKbLimit  int64  `json:"gif_size_kb_limit"`
	FileFormat      string `json:"file_format"`
	Pattern         string `json:"pattern"`
	Duration        string `json:"duration"`
	MinOccurs       string `json:"min_occurs"`
	MaxOccurs       string `json:"max_occurs"`
}
