// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type AccessTokenReq struct {
	AuthorizationCode string `json:"authorization_code"`
	State             string `json:"state"`
}

type RefreshTokenReq struct {
	ClientId int64 `json:"client_id"`
}

type AccessTokenResp struct {
	BaseResp
	AccessToken string `json:"access_token"`
}

type AccountListReq struct {
	AccountId   string `json:"account_id"`
	AccountName string `json:"account_name"`
	AccountType int64  `json:"account_type"`
	Page        int64  `json:"page"`
	PageSize    int64  `json:"page_size"`
	State       int64  `json:"state"`
}

type AccountListResp struct {
	BaseResp
	Total        int64          `json:"total"`
	AccountTypes map[int]string `json:"account_types"`
	State        map[int]string `json:"state"`
	Data         []AccountInfo  `json:"data"`
}

type AccountInfo struct {
	Id           int64  `json:"id"`
	AccountName  string `json:"account_name"`
	AccountType  int64  `json:"account_type"`
	AdvertiserId string `json:"advertiser_id"`
	DeveloperId  string `json:"developer_id"`
	ClientId     int64  `json:"client_id"`
	Secret       string `json:"secret"`
	State        int64  `json:"state"`
	IsAuth       int64  `json:"is_auth"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type AccountPost struct {
	AccountName  string `json:"account_name" validate:"required"`
	AccountType  int64  `json:"account_type" validate:"required"`
	AdvertiserId string `json:"advertiser_id" validate:"required"`
	DeveloperId  string `json:"developer_id"`
	ClientId     int64  `json:"client_id"`
	Secret       string `json:"secret"`
	State        int64  `json:"state"`
}

type AccountUpdateReq struct {
	Id int64 `json:"id" validate:"required"`
	AccountPost
}

type AccountInfoReq struct {
	Id int64 `json:"id" validate:"required,numberic"`
}

type AccountInfoResp struct {
	BaseResp
	Data AccountInfo `json:"data"`
}

type AuthResp struct {
	BaseResp
	Data string `json:"data"`
}

type PromotionCreateReq struct {
	CampaignName  string `json:"campaign_name" validate:"required"` // 计划名称
	ProductType   string `json:"product_type" validate:"required"`  // 推广产品
	DailyBudget   int64  `json:"daily_budget" validate:"numeric"`   // 日预算
	AdvertiserId  string `json:"advertiser_id"`                     // 广告主ID
	MarketingGoal string `json:"marketing_goal"`                    // 营销目标，默认为无目的
}

type PromotionCreateInfo struct {
	CampaignId string `json:"campaign_id"`
}

type PromotionCreateResp struct {
	Code int64               `json:"code"`
	Msg  string              `json:"msg"`
	Data PromotionCreateInfo `json:"data"`
}

type PromotionListReq struct {
	Page         int64  `json:"page"`
	PageSize     int64  `json:"page_size"`
	CampaignName string `json:"campaign_name"`
	CampaignId   string `json:"campaign_id"`
	ShowStatus   string `json:"show_status"`
}

type Promotion struct {
	Id                        int64  `json:"id"`
	CampaignName              string `json:"campaign_name"`                // 计划名称
	CampaignType              string `json:"campaign_type"`                // 计划类型
	FlowResource              string `json:"flow_resource"`                // 投放网络
	ProductType               string `json:"product_type"`                 // 推广产品
	UserBalanceStatus         string `json:"user_balance_status"`          // 账户余额状态
	CampaignStatus            string `json:"campaign_status"`              // 操作状态
	CampaignDailyBudgetStatus string `json:"campaign_daily_budget_status"` // 计划日预算状态
	ShowStatus                string `json:"show_status"`                  // 计划状态
	CreatedAt                 int64  `json:"created_at"`                   // 计划创建的时间
	MarketingGoal             string `json:"marketing_goal"`               //
	CampaignId                string `json:"campaign_id"`                  // 计划ID
	TodayDailyBudget          int64  `json:"today_daily_budget"`           // 当日计划日限额
	TomorrowDailyBudget       int64  `json:"tomorrow_daily_budget"`        // 次日计划日限额，不返回表示与当日计划日限额相同
	SyncFlowResourceSearchad  string `json:"sync_flow_resource_searchad"`  // 同时同步投放搜索广告网络 YES|NO
}

type PromotionListResp struct {
	BaseResp
	Total int64       `json:"total"`
	Data  []Promotion `json:"data"`
}
