// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountsFieldNames          = builder.RawFieldNames(&Accounts{})
	accountsRows                = strings.Join(accountsFieldNames, ",")
	accountsRowsExpectAutoSet   = strings.Join(stringx.Remove(accountsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	accountsRowsWithPlaceHolder = strings.Join(stringx.Remove(accountsFieldNames, "`id`", "`create_time`", "`update_time`", "`created_at`", "`update_at`"), "=?,") + "=?"

	cacheAccountsIdPrefix           = "cache:accounts:id:"
	cacheAccountsAdvertiserIdPrefix = "cache:accounts:advertiserId:"
	cacheAccountsClientIdPrefix     = "cache:accounts:clientId:"
)

type (
	accountsModel interface {
		Insert(ctx context.Context, data *Accounts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Accounts, error)
		FindOneByAdvertiserId(ctx context.Context, advertiserId string) (*Accounts, error)
		Update(ctx context.Context, newData *Accounts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAccountsModel struct {
		sqlc.CachedConn
		table string
	}

	Accounts struct {
		Id           int64     `db:"id"`
		AdvertiserId string    `db:"advertiser_id"` // 广告主账户ID
		DeveloperId  string    `db:"developer_id"`  // 开发者ID
		AccountType  int64     `db:"account_type"`  // 账户类型
		State        int64     `db:"state"`         // 状态
		AccountName  string    `db:"account_name"`  // 账户名
		ClientId     int64     `db:"client_id"`     // 客户端ID
		Secret       string    `db:"secret"`        // 密钥
		IsAuth       int64     `db:"is_auth"`       // 是否已认证
		CreatedAt    time.Time `db:"created_at"`    // 添加时间
		UpdatedAt    time.Time `db:"updated_at"`    // 最后一次修改时间
	}
)

func newAccountsModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAccountsModel {
	return &defaultAccountsModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`accounts`",
	}
}

func (m *defaultAccountsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	accountsAdvertiserIdKey := fmt.Sprintf("%s%v", cacheAccountsAdvertiserIdPrefix, data.AdvertiserId)
	accountsIdKey := fmt.Sprintf("%s%v", cacheAccountsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, accountsAdvertiserIdKey, accountsIdKey)
	return err
}

func (m *defaultAccountsModel) FindOne(ctx context.Context, id int64) (*Accounts, error) {
	accountsIdKey := fmt.Sprintf("%s%v", cacheAccountsIdPrefix, id)
	var resp Accounts
	err := m.QueryRowCtx(ctx, &resp, accountsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", accountsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountsModel) FindOneByAdvertiserId(ctx context.Context, advertiserId string) (*Accounts, error) {
	accountsAdvertiserIdKey := fmt.Sprintf("%s%v", cacheAccountsAdvertiserIdPrefix, advertiserId)
	var resp Accounts
	err := m.QueryRowIndexCtx(ctx, &resp, accountsAdvertiserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `advertiser_id` = ? limit 1", accountsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, advertiserId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountsModel) Insert(ctx context.Context, data *Accounts) (sql.Result, error) {
	accountsAdvertiserIdKey := fmt.Sprintf("%s%v", cacheAccountsAdvertiserIdPrefix, data.AdvertiserId)
	accountsIdKey := fmt.Sprintf("%s%v", cacheAccountsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, accountsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AdvertiserId, data.DeveloperId, data.AccountType, data.State, data.AccountName, data.ClientId, data.Secret, data.IsAuth, data.CreatedAt, data.UpdatedAt)
	}, accountsAdvertiserIdKey, accountsIdKey)
	return ret, err
}

func (m *defaultAccountsModel) Update(ctx context.Context, newData *Accounts) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	accountsAdvertiserIdKey := fmt.Sprintf("%s%v", cacheAccountsAdvertiserIdPrefix, data.AdvertiserId)
	accountsIdKey := fmt.Sprintf("%s%v", cacheAccountsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, accountsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AdvertiserId, newData.DeveloperId, newData.AccountType, newData.State, newData.AccountName, newData.ClientId, newData.Secret, newData.IsAuth, newData.UpdatedAt, newData.Id)
	}, accountsAdvertiserIdKey, accountsIdKey)
	return err
}

func (m *defaultAccountsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAccountsIdPrefix, primary)
}

func (m *defaultAccountsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", accountsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAccountsModel) tableName() string {
	return m.table
}
