apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: business
  labels:
    app: app-api
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      serviceAccountName: business
      containers:
      - name: app-api
        image: silentcxl/app-api:v1.0.2
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 18003
        readinessProbe:
          tcpSocket:
            port: 18003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 18003
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: configfiles
          mountPath: /app/etc
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: configfiles
          nfs:
            path: /usr/local/nfs/business/app-app-api
            server: 192.168.120.61
            readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: app-api-svc
  namespace: business
spec:
  ports:
    - nodePort: 30030
      port: 18003
      protocol: TCP
      targetPort: 18003
  type: NodePort
  selector:
    app: app-api

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-api-hpa-c
  namespace: business
  labels:
    app: app-api-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-api-hpa-m
  namespace: business
  labels:
    app: app-api-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
