apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-business
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /www/servers/business/
    server: 192.168.120.61

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-business
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi