apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-client
  namespace: business
  labels:
    app: rbac-client
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rbac-client
  template:
    metadata:
      labels:
        app: rbac-client
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: rbac-client
        image: silentcxl/rbac-client:v1.0.0
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 28001
        readinessProbe:
          tcpSocket:
            port: 28001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 28001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: rbac-client-svc
  namespace: business
spec:
  ports:
    - port: 28001
  selector:
    app: rbac-client

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rbac-client-hpa-c
  namespace: business
  labels:
    app: rbac-client-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rbac-client
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rbac-client-hpa-m
  namespace: business
  labels:
    app: rbac-client-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rbac-client
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
