// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type AccountInfoReq struct {
	Id int64 `json:"id"`
}

type AccountInfo struct {
	Id               int64         `json:"id"`
	AccountName      string        `json:"account_nName"`
	AccountId        string        `json:"account_id"`
	AccountType      int64         `json:"account_type"`
	Email            string        `json:"email"`
	State            int64         `json:"state"`
	AreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
	AccountClientIds []ActClientId `json:"account_client_ids"`
}

type ActClientId struct {
	Id       int64  `json:"id"`
	ClientId int64  `json:"client_id"`
	Secret   string `json:"secret"`
	Comment  string `json:"comment"`
}

type GetAccountInfoResp struct {
	BaseResp
	Data AccountInfo `json:"data"`
}
