// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type AccessTokenReq struct {
	AuthorizationCode string `json:"authorization_code"`
	State             string `json:"state"`
}

type RefreshTokenReq struct {
	ClientId string `json:"client_id"`
}

type AccessTokenResp struct {
	BaseResp
	AccessToken string `json:"access_token"`
}

type AccountListReq struct {
	AccountId   string `form:"account_id,optional"`
	AccountName string `form:"account_name,optional"`
	AccountType int64  `form:"account_type,optional"`
	State       int64  `form:"state"`
	Page        int64  `form:"page"`
	PageSize    int64  `form:"page_size"`
}

type AccountListResp struct {
	BaseResp
	Total        int64          `json:"total"`
	AccountTypes map[int]string `json:"account_types"`
	State        map[int]string `json:"state"`
	Data         []AccountInfo  `json:"data"`
}

type AccountInfo struct {
	Id           int64  `json:"id"`
	ParentId     int64  `json:"parent_id"`
	AccountName  string `json:"account_name"`
	AccountType  int64  `json:"account_type"`
	AdvertiserId string `json:"advertiser_id"`
	DeveloperId  string `json:"developer_id"`
	ClientId     string `json:"client_id"`
	Secret       string `json:"secret"`
	State        int64  `json:"state"`
	IsAuth       int64  `json:"is_auth"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type AccountPost struct {
	ParentId     int64  `json:"parent_id"`
	AccountName  string `json:"account_name" validate:"required"`
	AccountType  int64  `json:"account_type" validate:"required"`
	AdvertiserId string `json:"advertiser_id" validate:"required"`
	DeveloperId  string `json:"developer_id"`
	ClientId     string `json:"client_id"`
	Secret       string `json:"secret"`
	State        int64  `json:"state"`
}

type AccountUpdateReq struct {
	Id int64 `json:"id" validate:"required"`
	AccountPost
}

type AccountInfoReq struct {
	Id int64 `form:"id"`
}

type AccountInfoResp struct {
	BaseResp
	Data AccountInfo `json:"data"`
}

type AuthResp struct {
	BaseResp
	Data string `json:"data"`
}

type AccountSearchReq struct {
	AccountName string `form:"account_name"`
}

type AccountSearchResp struct {
	BaseResp
	Data []AccountInfo `json:"data"`
}
