// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tokensFieldNames          = builder.RawFieldNames(&Tokens{})
	tokensRows                = strings.Join(tokensFieldNames, ",")
	tokensRowsExpectAutoSet   = strings.Join(stringx.Remove(tokensFieldNames, "`id`", "`create_at`", "`update_at`"), ",")
	tokensRowsWithPlaceHolder = strings.Join(stringx.Remove(tokensFieldNames, "`id`", "`created_at`", "`update_at`"), "=?,") + "=?"
)

type (
	tokensModel interface {
		Insert(ctx context.Context, data *Tokens) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Tokens, error)
		FindOneByAccountId(ctx context.Context, accountId int64) (*Tokens, error)
		Update(ctx context.Context, newData *Tokens) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTokensModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tokens struct {
		Id           int64     `db:"id"`
		AccountId    int64     `db:"account_id"`    // 账户ID
		AdvertiserId string    `db:"advertiser_id"` //
		AccessToken  string    `db:"access_token"`
		RefreshToken string    `db:"refresh_token"`
		ExpiredAt    time.Time `db:"expired_at"` // access_token 过期时间
		CreatedAt    time.Time `db:"created_at"` // 添加时间
		UpdatedAt    time.Time `db:"updated_at"` // 最后一次修改时间
		TokenType    string    `db:"token_type"`
	}
)

func newTokensModel(conn sqlx.SqlConn) *defaultTokensModel {
	return &defaultTokensModel{
		conn:  conn,
		table: "`tokens`",
	}
}

func (m *defaultTokensModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTokensModel) FindOne(ctx context.Context, id int64) (*Tokens, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tokensRows, m.table)
	var resp Tokens
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTokensModel) FindOneByAccountId(ctx context.Context, accountId int64) (*Tokens, error) {
	var resp Tokens
	query := fmt.Sprintf("select %s from %s where `account_id` = ? limit 1", tokensRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, accountId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTokensModel) Insert(ctx context.Context, data *Tokens) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tokensRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.AdvertiserId, data.AccessToken, data.RefreshToken, data.ExpiredAt, data.CreatedAt, data.UpdatedAt, data.TokenType)
	return ret, err
}

func (m *defaultTokensModel) Update(ctx context.Context, newData *Tokens) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tokensRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AccountId, newData.AdvertiserId, newData.AccessToken, newData.RefreshToken, newData.ExpiredAt, newData.UpdatedAt, newData.TokenType, newData.Id)
	return err
}

func (m *defaultTokensModel) tableName() string {
	return m.table
}
